---
jitsi_meet_ssl_cert_path: ''
jitsi_meet_ssl_key_path: ''

jitsi_meet_base_packages:
  - apt-transport-https
  - default-jre-headless

jitsi_meet_server_name: "{{ ansible_fqdn if (jitsi_meet_ssl_cert_path) else 'localhost' }}"

jitsi_meet_use_nightly_apt_repo: false

jitsi_meet_apt_repos:
  stable:
    repo_url: 'deb https://download.jitsi.org/ stable/'
  unstable:
    repo_url: 'deb https://download.jitsi.org unstable/'

jitsi_meet_videobridge_secret: ''
jitsi_meet_jicofo_secret: ''
jitsi_meet_jicofo_password: ''

jitsi_meet_debconf_settings:
  - name: jitsi-meet/jvb-hostname
    question: jitsi-meet/jvb-hostname
    value: "{{ jitsi_meet_server_name }}"
    vtype: string
  - name: jitsi-meet/jvb-serve
    question: jitsi-meet/jvb-serve
    value: "false"
    vtype: boolean
  - name: jitsi-meet-prosody/jvb-hostname
    question: jitsi-meet-prosody/jvb-hostname
    value: "{{ jitsi_meet_server_name }}"
    vtype: string
  - name: jitsi-videobridge/jvb-hostname
    question: jitsi-videobridge/jvb-hostname
    value: "{{ jitsi_meet_server_name }}"
    vtype: string
  - name: jicofo/jicofo-authuser
    question: jicofo/jicofo-authuser
    value: "focus"
    vtype: string
  - name: jitsi-meet/cert-path-key
    question: jitsi-meet/cert-path-key
    value: "/etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem"
    vtype: string
  - name: jitsi-meet/cert-path-crt
    question: jitsi-meet/cert-path-crt
    value: "/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem"
    vtype: string
