---
- name: Copy Jicofo config file.
  template:
    dest: /etc/jitsi/jicofo/config
    src: jicofo_config.j2
    owner: root
    group: root
    mode: "0644"
  notify: restart jicofo

- name: Copy Jitsi Videobridge config file.
  template:
    dest: /etc/jitsi/videobridge/config
    src: videobridge_config.j2
    owner: root
    group: root
    mode: "0644"
  notify: restart jitsi-videobridge

- name: Set Jicofo log level.
  lineinfile:
    dest: /etc/jitsi/jicofo/logging.properties
    regexp: '^\.level'
    line: ".level=WARNING"
    state: present
  notify: restart jicofo

- name: Copy jicofo SIP communicator settings.
  template:
    dest: "/etc/jitsi/jicofo/sip-communicator.properties"
    src: sip-communicator.jicofo.j2
    owner: root
    group: root
    mode: "0644"
  notify: restart jicofo

- name: Create directory for SIP communicator settings.
  file:
    state: directory
    path: /usr/share/jicofo/.sip-communicator
    owner: jicofo
    group: jitsi

- name: Symlink SIP communicator settings.
  file:
    path: "/usr/share/jicofo/.sip-communicator/sip-communicator.properties"
    src: "/etc/jitsi/jicofo/sip-communicator.properties"
    state: link
    owner: root
    group: root