---
- name: Install base apt packages.
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ jitsi_meet_base_packages }}"

- name: Determine repo strategy.
  set_fact:
    jitsi_strategy: "{{ 'unstable' if jitsi_meet_use_nightly_apt_repo else 'stable' }}"

- name: Configure signing key for Jitsi repository.
  apt_key:
    id: 66A9CD0595D6AFA247290D3BEF8B479E2DC1389C
    url: "https://download.jitsi.org/jitsi-key.gpg.key"
    state: present

- name: Install Jitsi apt repo.
  apt_repository:
    repo: "{{ item.value.repo_url }}"
    state: "{{ 'present' if jitsi_strategy == item.key else 'absent' }}"
    filename: /etc/apt/sources.list.d/jitsi
  with_dict: "{{ jitsi_meet_apt_repos }}"

- name: Set debconf options for jitsi-meet.
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ jitsi_meet_debconf_settings }}"

- name: Install Jitsi Meet
  apt:
    name: jitsi-meet
    state: latest
    update_cache: yes
    cache_valid_time: 3600